# Task 1:

problem 1.

In [14]:
#write a function to compute 5/0 and use try/except to catch the exceptions

def addfunc(x,y):
    a=0
    try:
        a=x/y
        print(a)
    except:
        print('zero division error')
        
p=5
q=0
addfunc(p,q)
        

zero division error


problem 2.

In [15]:
#Implement a python program to generate all sentences where subject is in ["americans","indians"]
#verbs is in["play","watch"] and objects is in ["baseball","cricket"]

subjects=["americans","indians"]
verbs=["play","watch"]
objects=["baseball","cricket"]
statement=[sub+' '+verb+' '+obj for sub in subjects for verb in verbs for obj in objects]
for i in statement:
    print(i)


americans play baseball
americans play cricket
americans watch baseball
americans watch cricket
indians play baseball
indians play cricket
indians watch baseball
indians watch cricket


# Task 2:
problem 1

In [26]:
#Write a function so that columns of the output matrix are the powers of the input vector
#the order of the powers is determined by the increasing boolean argument.specifically when incresing is False
#the i-th output column is the input vector raised element-wise to the power of N-i-1

import numpy as np
a=np.array([1,2,3,4])
s=np.vander(a,increasing=False)
t=np.vander(a,increasing=True)
print('The powers of the i-th column, when increasing is False:')
print(s)
print('The powers of the i-th column,when increasing is True')
print(t)

The powers of the i-th column, when increasing is False:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
The powers of the i-th column,when increasing is True
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
